# pyproject.toml
[project]
name = "clairvoyent-raven-sports-analysis"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "pandas>=1.5.3",
    "numpy>=1.23.5",
    "requests>=2.28.2",
    "python-dotenv>=0.21.0",
    "pytest>=7.2.2",
]